import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const stockData = [
  { code: 'SVP 08', category: 'SOFFIT', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 0, loosePieces: '2', totalPieces: 2, totalSqft: 17.44, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 41, loosePieces: '1', totalPieces: 418, totalSqft: 4117.3, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 0, loosePieces: '4+10 (DEFECTED)', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 12, loosePieces: '0', totalPieces: 120, totalSqft: 1182.0, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 15, loosePieces: '4', totalPieces: 154, totalSqft: 1915.76, newUpcoming: '' },
  { code: 'SVPU 08', category: 'SOFFIT', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 1, loosePieces: '5', totalPieces: 15, totalSqft: 130.8, newUpcoming: '' },
  { code: 'SVPU 08', category: 'SOFFIT', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 1, loosePieces: '6', totalPieces: 16, totalSqft: 157.6, newUpcoming: '' },
  { code: 'SVPU 08', category: 'SOFFIT', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 5, loosePieces: '0', totalPieces: 54, totalSqft: 671.76, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'BASALT OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 6, loosePieces: '8', totalPieces: 68, totalSqft: 669.8, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'BASALT OAK', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 3, loosePieces: '0', totalPieces: 30, totalSqft: 373.2, newUpcoming: '' },
  { code: 'SVPU 08', category: 'SOFFIT', colour: 'DARK MAHOGANY', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 4, loosePieces: '2', totalPieces: 42, totalSqft: 413.7, newUpcoming: '' },
  { code: 'SVPU 08', category: 'SOFFIT', colour: 'DARK MAHOGANY', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 6, loosePieces: '1', totalPieces: 61, totalSqft: 758.8399999999999, newUpcoming: '' },
  { code: 'SV 08', category: 'SOFFIT', colour: 'GRAPHITE', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 0, loosePieces: '5', totalPieces: 5, totalSqft: 43.6, newUpcoming: '' },
  { code: 'SV 08', category: 'SOFFIT', colour: 'GRAPHITE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 3, loosePieces: '5', totalPieces: 35, totalSqft: 344.75, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'ROSEWOOD', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 0, loosePieces: '6', totalPieces: 6, totalSqft: 52.32000000000001, newUpcoming: '' },
  { code: 'SVP08', category: 'SOFFIT', colour: 'ROSEWOOD', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 6, loosePieces: '4', totalPieces: 64, totalSqft: 630.4, newUpcoming: '' },
  { code: 'SVP08', category: 'SOFFIT', colour: 'ROSEGOLD', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 5, loosePieces: '5', totalPieces: 55, totalSqft: 684.1999999999999, newUpcoming: '' },
  { code: 'SVP08', category: 'SOFFIT', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 9, loosePieces: '4', totalPieces: 94, totalSqft: 925.9, newUpcoming: '' },
  { code: 'SVP08', category: 'SOFFIT', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 9, loosePieces: '1', totalPieces: 91, totalSqft: 1132.04, newUpcoming: '' },
  { code: 'SV 08', category: 'SOFFIT', colour: 'WHITE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 9, loosePieces: '2', totalPieces: 92, totalSqft: 906.1999999999999, newUpcoming: '' },
  { code: 'SV 08', category: 'SOFFIT', colour: 'WHITE', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 10, loosePieces: '0', totalPieces: 99, totalSqft: 1231.56, newUpcoming: '' },
  { code: 'SV 08', category: 'SOFFIT', colour: 'ANTRACYT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 4, loosePieces: '0', totalPieces: 40, totalSqft: 394.0, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'POLAR OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 5, loosePieces: '8', totalPieces: 58, totalSqft: 571.3, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'POLAR OAK', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.45, boxes: 5, loosePieces: '0', totalPieces: 50, totalSqft: 622.5, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'BALANCE OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 13, loosePieces: '9', totalPieces: 139, totalSqft: 1369.1499999999999, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'BUTTER CREAM', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 7, loosePieces: '2', totalPieces: 72, totalSqft: 709.1999999999999, newUpcoming: '' },
  { code: 'SV-08', category: 'SOFFIT', colour: 'WHITE', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 0, loosePieces: '1', totalPieces: 1, totalSqft: 8.72, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'TYROL PINE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 5, loosePieces: '0', totalPieces: 50, totalSqft: 492.5, newUpcoming: '' },
  { code: 'SVP 08', category: 'SOFFIT', colour: 'BROWN', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 2, loosePieces: '0', totalPieces: 20, totalSqft: 197.0, newUpcoming: '' },
  { code: 'SVP 07', category: 'PERFORATION', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 4, loosePieces: '2', totalPieces: 42, totalSqft: 366.24, newUpcoming: '' },
  { code: 'SVP 07', category: 'PERFORATION', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 5, loosePieces: '4', totalPieces: 59, totalSqft: 514.48, newUpcoming: '' },
  { code: 'SVPU 07', category: 'PERFORATION', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 4, loosePieces: '6', totalPieces: 46, totalSqft: 401.12, newUpcoming: '' },
  { code: 'SVP 07', category: 'PERFORATION', colour: 'WHITE', variant: '', mtrs: 2.7, sqftPerPlank: 8.72, boxes: 0, loosePieces: '0', totalPieces: 20, totalSqft: 174.4, newUpcoming: '' },
  { code: 'SV 26', category: 'ROOF SOFFIT SV26', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 14, loosePieces: '1', totalPieces: 141, totalSqft: 1388.85, newUpcoming: '' },
  { code: 'SV 26', category: 'ROOF SOFFIT SV26', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 4, loosePieces: '9', totalPieces: 49, totalSqft: 609.56, newUpcoming: '' },
  { code: 'SV 26', category: 'ROOF SOFFIT SV26', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 14, loosePieces: '5', totalPieces: 145, totalSqft: 1428.25, newUpcoming: '' },
  { code: 'SV 26', category: 'ROOF SOFFIT SV26', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.85, sqftPerPlank: 12.44, boxes: 10, loosePieces: '3', totalPieces: 103, totalSqft: 1281.32, newUpcoming: '46PC' },
  { code: 'SV 26', category: 'ROOF SOFFIT SV26', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 5, loosePieces: '0', totalPieces: 50, totalSqft: 492.5, newUpcoming: '' },
  { code: 'SVP 06', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 20, loosePieces: '3', totalPieces: 203, totalSqft: 1611.8200000000002, newUpcoming: '' },
  { code: 'SXP 06', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'EXTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 14, loosePieces: '9', totalPieces: 149, totalSqft: 1183.06, newUpcoming: '' },
  { code: 'SVP 06 VB', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 0, loosePieces: '4', totalPieces: 4, totalSqft: 31.76, newUpcoming: '' },
  { code: 'SVP 06 VB', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 4, loosePieces: '0', totalPieces: 40, totalSqft: 328.40000000000003, newUpcoming: '' },
  { code: 'SXP 06 VB', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'EXTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '0', totalPieces: 100, totalSqft: 821.0000000000001, newUpcoming: '' },
  { code: 'SVP 06', category: 'FRONTO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 10, loosePieces: '0', totalPieces: 100, totalSqft: 794.0, newUpcoming: '' },
  { code: 'SXP 06', category: 'FRONTO', colour: 'WALNUT', variant: 'EXTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 22, loosePieces: '0', totalPieces: 300, totalSqft: 2463.0000000000005, newUpcoming: '' },
  { code: 'SVP 06 VB', category: 'FRONTO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 2, loosePieces: '9', totalPieces: 29, totalSqft: 230.26000000000002, newUpcoming: '' },
  { code: 'SVP 06 VB', category: 'FRONTO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '0', totalPieces: 100, totalSqft: 821.0000000000001, newUpcoming: '' },
  { code: 'SXP 06 VB', category: 'FRONTO', colour: 'WALNUT', variant: 'EXTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 14, loosePieces: '4', totalPieces: 144, totalSqft: 1143.3600000000001, newUpcoming: '' },
  { code: 'SVPU 06', category: 'FRONTO', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 7, loosePieces: '0', totalPieces: 70, totalSqft: 555.8000000000001, newUpcoming: '' },
  { code: 'SVP 06', category: 'FRONTO', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '4', totalPieces: 104, totalSqft: 853.8400000000001, newUpcoming: '' },
  { code: 'SVP 06', category: 'FRONTO', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 4, loosePieces: '0', totalPieces: 40, totalSqft: 328.40000000000003, newUpcoming: '' },
  { code: 'SXP 06', category: 'FRONTO', colour: 'OAK', variant: 'EXTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 10, loosePieces: '0', totalPieces: 100, totalSqft: 794.0, newUpcoming: '' },
  { code: 'SVP 06 VB', category: 'FRONTO', colour: 'OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '5', totalPieces: 85, totalSqft: 697.85, newUpcoming: '' },
  { code: 'SXP 06 VB', category: 'FRONTO', colour: 'OAK', variant: 'EXTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 8, loosePieces: '8', totalPieces: 88, totalSqft: 698.72, newUpcoming: '' },
  { code: 'SXP 06 VB', category: 'FRONTO', colour: 'OAK', variant: 'EXTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 2, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SV06', category: 'FRONTO', colour: 'BUTTER CREAM', variant: 'EXTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 5, loosePieces: '0', totalPieces: 50, totalSqft: 397.0, newUpcoming: '' },
  { code: 'SVP 24', category: 'FRONTO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 7, loosePieces: '6', totalPieces: 76, totalSqft: 603.44, newUpcoming: '' },
  { code: 'SVP 24', category: 'FRONTO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 10, loosePieces: '7', totalPieces: 107, totalSqft: 849.58, newUpcoming: '' },
  { code: 'SVPU 06', category: 'FRONTO', colour: 'HONEY OAK', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 7.94, boxes: 1, loosePieces: '0', totalPieces: 10, totalSqft: 79.4, newUpcoming: '' },
  { code: 'SVPU 06', category: 'FRONTO', colour: 'HONEY OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 0, loosePieces: '0', totalPieces: 1, totalSqft: 8.21, newUpcoming: '' },
  { code: 'SXPU 06', category: 'FRONTO', colour: 'HONEY OAK', variant: 'EXTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 5, loosePieces: '9', totalPieces: 59, totalSqft: 484.39000000000004, newUpcoming: '' },
  { code: 'SV 06', category: 'FRONTO', colour: 'ANTHRACITE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 7.94, boxes: 5, loosePieces: '0', totalPieces: 50, totalSqft: 397.0, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 7.26, boxes: 9, loosePieces: '5', totalPieces: 95, totalSqft: 689.6999999999999, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 12, loosePieces: '0', totalPieces: 60, totalSqft: 492.6, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 2.7, sqftPerPlank: 7.26, boxes: 0, loosePieces: '3', totalPieces: 3, totalSqft: 21.78, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 11, loosePieces: '0', totalPieces: 110, totalSqft: 903.1000000000001, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'OAK WINCHESTER', variant: 'INTERIOR', mtrs: 2.95, sqftPerPlank: 8.21, boxes: 10, loosePieces: '7', totalPieces: 107, totalSqft: 878.4700000000001, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'DARK MAHOGANY', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 3, loosePieces: '4', totalPieces: 34, totalSqft: 279.14000000000004, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'BALANCE OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 6, loosePieces: '2', totalPieces: 62, totalSqft: 509.02000000000004, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'POLAR OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '4', totalPieces: 104, totalSqft: 853.8400000000001, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'GRAPHITE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 8, loosePieces: '7', totalPieces: 87, totalSqft: 714.2700000000001, newUpcoming: '' },
  { code: 'SVP22', category: 'WELO', colour: 'LIGHT OLIVE', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 6, loosePieces: '8', totalPieces: 68, totalSqft: 558.2800000000001, newUpcoming: '' },
  { code: 'SVP 22', category: 'WELO', colour: 'BUTTER CREAM', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 9, loosePieces: '5', totalPieces: 45, totalSqft: 369.45000000000005, newUpcoming: '' },
  { code: 'SXP05', category: 'MAX 3', colour: 'GOLDEN OAK', variant: 'EXTERIOR', mtrs: 3.85, sqftPerPlank: 10.37, boxes: 4, loosePieces: '2', totalPieces: 42, totalSqft: 435.53999999999996, newUpcoming: '' },
  { code: 'SXPU 05', category: 'MAX 3', colour: 'OAK WINCHESTER', variant: 'FAÇADE', mtrs: 3.85, sqftPerPlank: 10.36, boxes: 8, loosePieces: '2', totalPieces: 82, totalSqft: 849.52, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'NATURAL', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 14, loosePieces: '0', totalPieces: 224, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'NATURAL', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 10, loosePieces: '0', totalPieces: 160, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'NATURAL', variant: 'L LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 1, loosePieces: '0', totalPieces: 12, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'CHOCOLATE', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 7, loosePieces: '0', totalPieces: 124, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'MOCCA', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 9, loosePieces: '0', totalPieces: 148, totalSqft: 833.099, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'MOCCA', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 78, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'NATURAL BLACK', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 15, loosePieces: '0', totalPieces: 240, totalSqft: 961.268, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'NATURAL BLACK', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 80, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'WHITE', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 0, loosePieces: '0', totalPieces: 1, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'WHITE', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 10, loosePieces: '0', totalPieces: 166, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'GREY', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 4, loosePieces: '0', totalPieces: 72, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'GREY', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 4, loosePieces: '0', totalPieces: 60, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'BLACK', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 72, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'BLACK', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 80, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'ANTHRACITE', variant: 'S-LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 80, totalSqft: 320.423, newUpcoming: '' },
  { code: 'SP- LINERIO', category: 'LINERIO', colour: 'ANTHRACITE', variant: 'M LINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 80, totalSqft: 320.423, newUpcoming: '' },
  { code: 'CEILING', category: 'CEILING', colour: 'SQUARE LOUVERS', variant: 'VOLOS', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 11, loosePieces: '0', totalPieces: 238, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'WALNUT', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 25, loosePieces: '2', totalPieces: 252, totalSqft: 2482.2, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'WINCHESTER OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 11, loosePieces: '4', totalPieces: 114, totalSqft: 1122.8999999999999, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'BEIGE OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 0, loosePieces: '7', totalPieces: 7, totalSqft: 68.95, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'ARTISAN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 15, loosePieces: '0', totalPieces: 150, totalSqft: 1477.5, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'GOLDEN OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 11, loosePieces: '9', totalPieces: 119, totalSqft: 1172.1499999999999, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'RED ROSEWOOD', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 15, loosePieces: '8', totalPieces: 158, totalSqft: 1556.3, newUpcoming: '' },
  { code: 'SVF 08', category: 'VOLOS SOFFIT', colour: 'TEAK OAK', variant: 'INTERIOR', mtrs: 3.05, sqftPerPlank: 9.85, boxes: 6, loosePieces: '1', totalPieces: 61, totalSqft: 600.85, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'LIGHT PINE', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 14, loosePieces: '5', totalPieces: 145, totalSqft: 1190.45, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'NATURAL CEDAR', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 10, loosePieces: '7', totalPieces: 107, totalSqft: 878.4700000000001, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'CINNAMON WOOD', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 9, loosePieces: '8', totalPieces: 98, totalSqft: 804.58, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'PURE CARERRA', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 9, loosePieces: '9', totalPieces: 99, totalSqft: 812.7900000000001, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'GREY CARERRA', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 15, loosePieces: '0', totalPieces: 150, totalSqft: 1231.5000000000002, newUpcoming: '' },
  { code: 'SVF-22', category: 'VOLOS WELO', colour: 'DESERT SAND', variant: '', mtrs: 3.05, sqftPerPlank: 8.21, boxes: 8, loosePieces: '3', totalPieces: 83, totalSqft: 681.4300000000001, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS TEAKWOOD', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS OAK KOTTO', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 13, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '1 MISNAMED OAK PRIAR' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS PINE OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS POLAR OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 7, loosePieces: '0', totalPieces: 140, totalSqft: 326.55, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS DUNE OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS CARBON OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS CHESTNUT', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS ASH OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS MAHAGONY', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS VINTAGE OAK', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS HAZELNUT', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 12, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT FLOORING', colour: 'WS OAK PRIAR', variant: '2MM/.3MM', mtrs: 0.0, sqftPerPlank: 2.3325, boxes: 11, loosePieces: '0', totalPieces: 240, totalSqft: 559.8, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS OAK KOTTO', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 9, loosePieces: '0', totalPieces: 360, totalSqft: 540.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS PINE OAK', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 9, loosePieces: '0', totalPieces: 360, totalSqft: 540.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS DUNE OAK', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 9, loosePieces: '0', totalPieces: 360, totalSqft: 540.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS ASH OAK', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 9, loosePieces: '0', totalPieces: 360, totalSqft: 540.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS MAHAGONY', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 9, loosePieces: '0', totalPieces: 360, totalSqft: 540.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'WS VINTAGE OAK', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 1.5, boxes: 6, loosePieces: '0', totalPieces: 240, totalSqft: 360.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS STONE ASH', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS MARBLE WINTER', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS MARBLE LAVA', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS MARBLE CARRARA', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS STONE GREY', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'LVT', category: 'LVT WALL', colour: 'SS STONE CHARCOAL', variant: '1.2MM/.1MM', mtrs: 0.0, sqftPerPlank: 4.0, boxes: 6, loosePieces: '0', totalPieces: 138, totalSqft: 552.0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'WESTERN OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 18, loosePieces: '0', totalPieces: 0, totalSqft: 606.42, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'CHERRY OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 10, loosePieces: '2 BOX DAMAGE', totalPieces: 0, totalSqft: 336.9, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'CARAMEL OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 30, loosePieces: '0', totalPieces: 0, totalSqft: 1010.7, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NATURE OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 2, loosePieces: '14', totalPieces: 0, totalSqft: 67.38, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'CONCRETE OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 13, loosePieces: '14', totalPieces: 0, totalSqft: 437.97, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'MALT OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 1, loosePieces: '1', totalPieces: 0, totalSqft: 33.69, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'WALNUT OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 24, loosePieces: '0', totalPieces: 0, totalSqft: 808.56, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'OAK EBONY', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 9, loosePieces: '0', totalPieces: 0, totalSqft: 303.21, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'GOLDEN OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 0, loosePieces: '0', totalPieces: 0, totalSqft: 0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NORDIAC OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 1, loosePieces: '0', totalPieces: 0, totalSqft: 33.69, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'IMPERIAL OAK', variant: '1220*183MM', mtrs: 0.0, sqftPerPlank: 33.69, boxes: 33, loosePieces: '0', totalPieces: 0, totalSqft: 1111.77, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW NODIAC OAK', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 0, loosePieces: '10pc in a box', totalPieces: 0, totalSqft: 0, newUpcoming: '26 BOXES BOOKED FOR GRID LINE ON 11TH MARCH STOCK DELETED' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW OAK MIST', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 38, loosePieces: '0', totalPieces: 0, totalSqft: 886.54, newUpcoming: '16' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW GOLDEN OAK', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 2, loosePieces: '0', totalPieces: 0, totalSqft: 46.66, newUpcoming: '44' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW MALT OAK', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 0, loosePieces: '0', totalPieces: 0, totalSqft: 0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW OAK EBONY', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 10, loosePieces: '0', totalPieces: 0, totalSqft: 233.3, newUpcoming: '33' },
  { code: 'SPC', category: 'SPC FLOORING', colour: 'NEW NATURE OAK', variant: '4MM+1', mtrs: 0.0, sqftPerPlank: 23.33, boxes: 25, loosePieces: '0', totalPieces: 0, totalSqft: 583.25, newUpcoming: '18' },
  { code: 'SPC', category: 'SPC FLOORING HB', colour: 'GOLDEN OAK', variant: 'HB A & B', mtrs: 0.0, sqftPerPlank: 26.0, boxes: 22, loosePieces: '10.495', totalPieces: 0, totalSqft: 572.0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING HB', colour: 'MALT OAK', variant: 'HB A & B', mtrs: 0.0, sqftPerPlank: 39.0, boxes: 38, loosePieces: '10.495', totalPieces: 0, totalSqft: 1482.0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING HB', colour: 'WALNUT OAK', variant: 'HB A & B', mtrs: 0.0, sqftPerPlank: 44.0, boxes: 44, loosePieces: '10.495', totalPieces: 0, totalSqft: 1936.0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING HB', colour: 'NORDIAC OAK', variant: 'HB A & B', mtrs: 0.0, sqftPerPlank: 25.0, boxes: 25, loosePieces: '10.495', totalPieces: 0, totalSqft: 625.0, newUpcoming: '' },
  { code: 'SPC', category: 'SPC FLOORING HB', colour: 'IMPERIAL OAK', variant: 'HB A & B', mtrs: 0.0, sqftPerPlank: 20.0, boxes: 20, loosePieces: '10.495', totalPieces: 0, totalSqft: 400.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'GOLDEN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 165, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'WALNUT', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 321, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'DARK MAHAGONY', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 40, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 175, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'OAK WINCHESTER', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 80, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'BASALT OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 49, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'GRAPHITE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 31, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'ROSEWOOD', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 21, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'POLAR OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 107, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'BALANCE OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 103, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'BUTTER CREAM', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 53, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'WHITE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 116, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'HONEY OAK', variant: 'DELETED FOR SUNSHINE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 16, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'LIGHT OLIVE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 70, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SV 15', category: 'TRIMS', colour: 'CRANZY BLACK', variant: 'ANTHRACITE', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 49, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 15', category: 'TRIMS', colour: 'TYROL PINE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 30, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SV 15', category: 'TRIMS', colour: 'BROWN', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 30, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'WALNUT', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 54, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'WINCHESTER OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 40, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'BEIGE OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 14, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'ARTISAN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 76, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'GOLDEN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 41, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'RED ROSEWOOD', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 101, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'LIGHT PINE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 100, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'NATURAL CEDAR', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 53, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'CINNAMON WOOD', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 63, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'PURE CARRA', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 70, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'GREY CARRA', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 100, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'DESERT SAND', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 100, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15', category: 'TRIMS', colour: 'TEAK OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 50, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVF 15.5 L MINI', category: 'TRIMS', colour: 'LIGHT PINE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 50, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 12', category: 'TRIMS', colour: 'OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 35, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 12', category: 'TRIMS', colour: 'WALNUT', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 13, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP12', category: 'TRIMS', colour: 'GOLDEN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 25, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SV 11', category: 'TRIMS', colour: 'WHITE COLOUR STARTER TRIM', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 65, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 11.5', category: 'TRIMS', colour: 'VENTILATION TRIM( GREY)', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 47, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 18', category: 'TRIMS', colour: 'WHITE', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 27, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVPU 18', category: 'TRIMS', colour: 'OAK WINCHESTER', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 30, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 18', category: 'TRIMS', colour: 'WALNUT', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 39, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 18', category: 'TRIMS', colour: 'OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 22, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 18', category: 'TRIMS', colour: 'GOLDEN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 15, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 18', category: 'TRIMS', colour: 'HONEY OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 3, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 13', category: 'TRIMS', colour: 'GOLDEN OAK', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 6, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 13', category: 'TRIMS', colour: 'OAK WINCHESTER', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 5, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
  { code: 'SVP 13', category: 'TRIMS', colour: 'WALNUT', variant: 'TRIM', mtrs: 0.0, sqftPerPlank: 0.0, boxes: 2, loosePieces: '0', totalPieces: 0, totalSqft: 0.0, newUpcoming: '' },
];
// Total: 196 products

async function main() {
  console.log("🌱 Seeding database...");

  const hashedPassword = await bcrypt.hash("royale2024", 10);
  await prisma.user.upsert({
    where: { email: "admin@royalecladdings.com" },
    update: {},
    create: {
      email: "admin@royalecladdings.com",
      password: hashedPassword,
      name: "Admin",
      role: "ADMIN",
    },
  });
  console.log("✅ Admin user created: admin@royalecladdings.com / royale2024");

  await prisma.pICounter.upsert({
    where: { id: "counter" },
    update: {},
    create: { id: "counter", count: 0 },
  });

  await prisma.product.deleteMany();

  for (const item of stockData) {
    await prisma.product.create({ data: item });
  }

  console.log("✅ Seeded " + stockData.length + " products");
  console.log("🎉 Database seeded successfully!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
